### ISSUE TITLE
SPI pins different from "standard" ESP-WROOM-32D dev boards?

### ISSUE THREAD

**Issue by LK-Simon** [LaskaKit/ESP32-LPKit#1]
Hi,

I'm trying to get the nRF24L01+ radio working with this lovely ESP32-LPKit board.

I have verified the pin numbers as follows:

MOSI: 23
MISO: 19
CS/SCK: 18
SS: 5

I then connect CE to pin 22 (I've tried it on numerous different pins, on different registers... the result is the same).

I use the RF24 library (same as I'm using for the RF-Nano boards, and all of my other Arduino Uno/Duo/Nano/Nano-Every boards.

I configure the radio as follows:

```
RF24 radio(22, 18);
static bool success = false;

void setup() {
  Serial.begin(115200);
  while (!Serial) 
  {
    ; // waiting for serial com port
  }

  // Output SPI pins (to visually confirm I've got my wiring correct)
  Serial.println("MOSI: " + String(MOSI));
  Serial.println("MISO: " + String(MISO));
  Serial.println("SCK: " + String(SCK));
  Serial.println("SS: " + String(SS));

  uint8_t failures = 0;

  while (!success && failures < 10) {
    success = radio.begin();
    if (!success) {
        failures++;
        Serial.println("Radio Initialization Failure: " + String(failures));
        delay(100);
    }
  }

  if (!success) {
    Serial.println("Radio failed too many times!");
    return;
  }

  Serial.println("Radio Successful!");

  radio.setDataRate(RF24_2MBPS);
  radio.setPALevel(RF24_PA_MAX);

  radio.setPayloadSize(sizeof(ComPacket)); // "ComPacket" is a struct (omitted in this issue because it is shared code that isn't relevant to the problem)
  radio.setAutoAck(true);

  radio.openReadingPipe(1, 54321); // My Transmitter uses 54321 for the Writing Pipe
  radio.openWritingPipe(12345); // My Transmitter uses 12345 for the Reading Pipe

  radio.startListening(); // For this test, I want the Radio to receive only

  radio.printPrettyDetails(); // I'm printing the Radio details to visually confirm that my settings are correct (they are)
}
```

The above code runs and returns everything successfully. It looks great.

However, when my transmitter (which is an RF-Nano board that transmits a ComPacket struct every time a button is pressed, that packet being received successfully on another RF-Nano board with the same code I'm including in here) transmits a packet, the ESP32-LPkit board receives nothing (radio.available() returns false, even when I know there's data waiting on the 54321 pipe)

Here's my Loop

```
void loop() {
  if (!success) { return; } // If the Radio failed to initialize, there's no point in continuing the loop.
  
  if (radio.available()) { // This ALWAYS returns FALSE, even when I KNOW data SHOUD be available.
    Serial.println("Radio Data Available");
    ComPacket packet;
    radio.read(&packet, sizeof(ComPacket));
    PrintPacket(&packet);
  }
}
```

So, my question is: are the SPI pins on this LPKit board different to the numbers shown?

Before anyone responds saying "use ESP-NOW instead of the nRF24L01!" I _need_ the nRF24L01 to receive data packets from existing remote sensor units! The entire point is to effectively intermediate between my existing sensor boards, and the ESP32-WROOM-32D for _new_ sensor boards going forward. Sadly, I can't just replace the existing hardware in one go... I have to phase it out.

Also, please note that I deliberately created this test project as an Arduino-framework base, rather than the ESP framework... because I wanted to be able to immediately deploy the exact same code to the RF-Nano board to verify that it works (it does work on the RF-Nano, just not the ESP32-LPKit)

I appreciate any assistance on this. I've spent two whole days trying to figure it out, to no avail.

**Comment by Konstantin-G** [comment]
Hello,
thanks for reaching us out.
Please read RF24 library documentations about ESP32 and try again.
RF24 library suggest to use HSPI pins.
HSPI_MISO = 12
HSPI_MOSI = 13
HSPI_SCLK = 14
HSPI_SS   = 15
https://nrf24.github.io/RF24/md_docs_arduino.html
See schematic this board and [ESP32-WROOM-32](https://www.laskarduino.cz/user/related_files/esp32-wroom-32_datasheet_en.pdf)  about pins definition.
Come back if you have any problem with ESP32-LPKit

**Comment by LK-Simon** [comment]
I'll attempt this now and get back to you with the results. I wasn't aware that I should use the HSPI pins on ESP32... mainly because I've always used the SPI pins for the nRF24L01.
If this works, then your response is undoubtedly going to be helpful for many others :)

**Comment by Konstantin-G** [comment]
There are 3 SPI interfaces on ESP32.
more here https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

**Comment by Konstantin-G** [comment]
10 days w/o feedback, I'm closing issue.
